version: "3"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-DB
    env_file:
      - .env
    volumes:
      - ./db/data/postgres:/var/lib/postgresql/data  
    ports:
      - "5432:5432"
  bot:
    build: .
    environment:
      - PORT_POSTGRES=5432
      - HOST_POSTGRES=db
    volumes:
      - ./node:/home/app/node
    command: ["./wait-for-db.sh", "npm",  "run", "start"]
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always